export enum RPiComponentType {
	ALL = <any>"ALL",
	TEMPERATURE = <any>"TEMPERATURE",
  TEMPERATURE_HUMIDITY = <any>"TEMPERATURE_HUMIDITY",
	HUMIDITY = <any>"HUMIDITY",
	MOISTURE = <any>"MOISTURE",
	PROXIMITY = <any>"PROXIMITY",
	RELAY = <any>"RELAY"
}
